name: Selenium CI Demoblaze

on: [push]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4  # <--- v4 es la correcta para Node 20/24

      - name: Instalar Python 3.11
        uses: actions/setup-python@v5  # <--- v5 es la correcta para Node 20/24
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install selenium pytest

      - name: Correr mis tests
        run: |
          pytest src/test_demoblaze.py
