name: Selenium CI Demoblaze

on: [push]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Instalar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install selenium pytest

      - name: Correr mis tests
        run: |
          # Al estar en la raíz de DemoblazeAutomation, entramos a src/
          pytest src/test_demoblaze.py
